# Configuração do banco de dados H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG